/* config.h.  Generated by configure.  */
/* config.h.in.  Generated manually (TODO: use autoheader)  */

/* Define if you have the ANSI C header files.  */
#define STDC_HEADERS 1

/* Name of package */
#define PACKAGE "ultimatestunts"

/* Version number of package */
#define VERSION "0.6.0"

#define PREFIXDIR "/usr/local"

#define HAVE_GLEXT_H 1

/* #undef FMOD_HEADER */

/* #undef HAVE_LIBFMOD */

#define OPENAL_HEADER 1

#define HAVE_LIBOPENAL 1

#define HAVE_SDL 1
